# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
# gem install pg
# On Mac OS X with macports:
# gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
# gem install pg
# Choose the win32 build.
# Install PostgreSQL and put its /bin directory on your path.
development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dsum2kpouveg8
  username: wfnervozidxqdy
  password: P5WFq9FDgg9pE4m9uzpLyFJv0D
  host: ec2-54-225-101-64.compute-1.amazonaws.com
  port: 5432

# Connect on a TCP socket. Omitted by default since the client uses a
# domain socket that doesn't need configuration. Windows does not have
# domain sockets, so uncomment these lines.
#host: localhost
#port: 5432

# Schema search path. The server defaults to $user,public
#schema_search_path: myapp,sharedapp,public

# Minimum log levels, in increasing order:
# debug5, debug4, debug3, debug2, debug1,
# log, notice, warning, error, fatal, and panic
# The server defaults to notice.
#min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dcbh0agjntnlce
  username: mpccgjgkcubcub
  password: 8OOD__h8yelnNME5F8T52Y1EJY
  host: ec2-54-225-101-199.compute-1.amazonaws.com
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dcbh0agjntnlce
  username: mpccgjgkcubcub
  password: 8OOD__h8yelnNME5F8T52Y1EJY
  host: ec2-54-225-101-199.compute-1.amazonaws.com
  port: 5432
cucumber:
  <<: *test